-- Elimina la tabella se esiste per garantire una ripartenza pulita
DROP TABLE IF EXISTS public.prodotto CASCADE;

-- Crea la tabella con le colonne nell'ordine desiderato
CREATE TABLE public.prodotto
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(255) NOT NULL,
    descrizione character varying(255),
    prezzo numeric(10,2),
    immagine_url character varying(255),
    CONSTRAINT prodotto_pkey PRIMARY KEY (id)
);